name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ruby-ci:
    uses: Captive-Studio/captive-ci/.github/workflows/ruby-ci.yml@815e45ec997f694d62b0c2606d79605c1d723eab # main
    with:
      lint-command: bundle exec rubocop -f github
