name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ruby-ci:
    uses: Captive-Studio/captive-ci/.github/workflows/ruby-ci.yml@ba15172965337f393c77e03fa4edcdef17edc4e4 # main
    with:
      lint-command: bundle exec rubocop -f github
