name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ruby-ci:
    uses: Captive-Studio/captive-ci/.github/workflows/ruby-ci.yml@cd36f8582e92eadee6e6d594d3e951bb9ce7bbc7 # main
    with:
      lint-command: bundle exec rubocop -f github
